# Generated by Django 3.2.12 on 2024-01-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_categorytb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.FileField(upload_to='')),
                ('genre', models.CharField(max_length=20)),
                ('released', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('story', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.categorytb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.registertb')),
            ],
        ),
    ]
