# Generated by Django 3.2.12 on 2024-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_showtb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtb',
            name='genre',
            field=models.CharField(max_length=50),
        ),
    ]
