# Generated by Django 3.2.12 on 2024-01-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_alter_showtb_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtb',
            name='user_id',
        ),
    ]
