# Generated by Django 3.2.12 on 2024-01-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0003_showtb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time', models.DateField()),
                ('date', models.TimeField()),
                ('poster', models.FileField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.registertb')),
            ],
        ),
    ]
