# Generated by Django 3.2.12 on 2024-01-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtb',
            name='date',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewtb',
            name='time',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
