# Generated by Django 3.2.12 on 2024-01-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_showtb'),
        ('app_user', '0002_auto_20240107_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.showtb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.registertb')),
            ],
        ),
    ]
